import Head from 'next/head';

import NotificationRequest from '@/components/NotificationRequest';
import ServiceWorker from '@/components/ServiceWorker';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>PaulWangApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="application-name" content="PaulWangApp" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="PaulWangApp" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <link rel="apple-touch-icon" href="/icons/maskable_icon.png" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <Component {...pageProps} />
      <NotificationRequest />
      <ServiceWorker />
    </>
  );
}
